import random

login = ('Bir zamanlar monoton hayatından sıkılan bir karga varmış. Bir gün artık canına tak etmiş karganın her şeyi geride bırakıp evinden kaçma kararı almış. Çok uzun yollar gitmiş ve sonunda bir çiftliğe varmış.  Çiftliğe meraklı meraklı bakarken tavus kuşlarını görmüş. Kendisinin aksine bunların tüyleri renkli renkliymiş. Karga, o kadar çok beğenmiş ki bunları uzaktan bakmaya dayanamayıp yanlarına gitmiş. Onlara kim olduklarını sormuş içlerinden biri bizler tavus kuşuyuz çirkin şey diye cevap verip kendi aralarında gülerek uzaklaşmışlar. Arkalarından “bende sizden biri olmak istiyorum” diye bağırmış', 'Karnını doyurmak için yiyecek bir şeyler bulmaya çıkan kurt, gecenin karanlığında sessiz sessiz yürüyormuş. Çok açmış. Ayın bedenine vuran ışıklarından nerdeyse kemikleri sayılıyormuş. Patikaya doğru ilerlerken; iyi beslendiği her halinden belli olan heybetli ve tüyleri oldukça bakımlı bir köpekle karşılaşmış. Onun bu haline imrenen kurt; Ne şanslısın! Sana bakacak ve karnını doyuracak insanlar, gece güvenle uyuduğun bir yuvan var. Bu halinden ne kadar da memnun görünüyorsun” demiş. Köpek, kurda doğru merhametli bir bakış atarak kurdun bu çelimsiz haline üzüldü. Yaşadığım yerde yiyecek bulmakta zorluk çekmiyorum, düzenli bir hayatım var dedi. Eğer sen de benim gibi düzenli bir hayat istersen benimle gelebilirsin. İstediğin kadar doyarsın ve kulübemi paylaşırız” demiş', 'Bir varmış bir yokmuş çok eski zamanlarda şehirde yaşayan sevimli bir küçük fare varmış. Bu fare hayatından o kadar memnuniyetsizmiş ki sürekli olarak canı sıkılırmış. Arkadaşlarının olmaması şehir faresinin her gün sıkıntılı bir zaman geçirmesine neden olmuş. Zaman zaman arkadaş ihtiyacı duyan şehir faresi bu isteğini bir türlü şehirde gerçekleştiremiyormuş. Bu nedenle de gezinti yapmak için çantasını hazırlamış ve yaşadığı evden ayrılmış. En sonunda kendisinin evine yakın bir tarlada çalışan bir tarla faresi ile tanışmış. Bu tarla faresi hem çok akıllı hem de çok cana yakınmış. Bu nedenle de hemen ikisi birden arkadaş oluvermişler. Köylü fare çalışıyor şehirli fare konuşuyormuş. Sürekli kendinden ve renkli şehir hayatından bahseder olmuş. Köylü fare artık bundan rahatsız olmaya başlamış.')

development = ('Küçük kahraman buna çok üzülmüş. O da öyle bakımlı olmak istemiş. Düşünceli düşünceli yol alırken bir camda yansımasını görmüş. Beğenmemiş bu halini. Bir şey yapmalı onlara gününü göstermeli diye düşünmüş. Ama ne yapabilirdi ki? küçük kahraman üzerini renklendirmiş. Aynadan bakmış kendine Tavuz kuşu kadar renkli hissetmiş. Gitmiş havalı dostunun yanına “benimle dalga geçtiniz durdunuz, söyleyin şimdi kim daha güzel” demiş. Havalı dostları gülmeye başlamış. Dalga geçerek kovmuşlar yanlarından. Kahraman yine üzgün kalmış. Bu defada eski arkadaşlarına gidip hava atmış “bakın ben sizden daha güzelim” diye haykırmış. Onlarda bu küstahlığa dayanamayıp kovmuşlar yanından.', 'Kahraman yol boyunca nasıl dost olabileceklerini düşünmüş. Onun gibi parlak tüylere sahip olmak istemiş. Uzaktan onu izlemeye devam etmiş. Birlikte belki de cidden mutlu olabiliriz diye düşünmeden edememiş. Yemeği yemek aynı yerde kalmak. Bir dost edinmek harika olurmuş. O sırada arkadaşının boynundaki yarayı fark etmiş. Sormadan edememiş. “Boynuna ne oldu, yaralı görünüyorsun acıyor mu?” arkadaşı başını sallamış “hayır artık acımıyor tasmadan olsa gerek” demiş. Kahraman şaşırmış. “Nasıl yani sen özgür değil misin?” diye sormuş. “Bu sınırlar arasında özgürüm” diye cevap vermiş arkadaşı.', 'Arkadaşının yanında köylü kalan minik kahraman. Onun sürekli kendinden renkli parlak tüylerinden. Kirlenmemiş üzerinden bahsetmesinden yorulmuş. O da renkli bir hayat istemiş. Bir gün bunu parlak dostuna anlatmış. Ilık başta bu fikir komik gelse de “bu pasaklıya evimin şahaneliğini göstermek bana da mutluluk verir” diye düşünmüş ve ona nazikçe “tabi seni bizden biri yaparım” diyerek evine götürmeye karar verdiğini açıklamış. İki arkadaş gülerek yola çıkmışlar. Ama yoldaki tehlikelerden de ziyade arkadaşının evindeki tehlikelerin daha da fazla olduğunu fark etmiş. Arkadaşı ölüm korkusundan hiç bahsetmemiş.')

end = ('Küçük kahraman kimsesiz kalınca anlamış hatasını. Kurtulmuş üzerindekilerden. Eski haline gelmiş. Başkasının lafıyla hareketiyle hareket etmenin ne kadar kötü olduğunu anlamış. Bakmış yansımasına. Hayır en güzel hali kendi olduğu haliymiş. Eski dostlarına gidip yaptıklarından dolayı özür dilemiş. Arkadaşları bir süre laflasana da kabul etmişler.', 'Kahraman arkasını dönüp hemen uzaklaşmaya başlamış. Tüylü dostu bağırmış arkasından “nereye gidiyorsun hani bizden olacaktın. Nereye?” kahraman uzaklaşırken bağırmış arkasında kalana dönerek “senin adına sevindim benim tutsak arkadaşım. Tüm yiyecekler, mutlu yuvan ve seni sevdiğini söyleyen o sahipler senin olsun. Ben özgürlüğümü tüm bu şeylerin hiçbirisine değişmem. Ve ne için olursa olsun o zinciri boynuma takmayı kabul etmem” diyerek gitmiş yoluna.', 'Memleketi bildiği yerden uzaklaşmak küçük kahramanın hiç hoşuna gitmemiş. Bu yeni geldiği yer hiç güzel değilmiş. Arkadaşından özür diledi. İstediği şeyin bu olmadığını belirtti. Döndü arkasını ve gitti. Neden kendini küçümsemiş. Onu gözünde büyüttü anlamamıştı. Kendi hayatı ve daha güzeldi. Bunu bir şeyleri kaybetmeden anladığı için teşekkür etti. ')


print(random.choice(login))

print(random.choice(development))

print(random.choice(end))
